apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpdserver
  labels: 
    k8s-app: http-caitlin
spec:
  template:
    metadata: 
      labels:
        k8s-app: http
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname:  xcache-11.t2.ucsd.edu
      containers:
      - name: httpd-server
        image: cahung/kubernetes
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        command: ["/usr/sbin/httpd", "-DFOREGROUND"]
        env:
        - name: DATA1
          value: /data1/stash 
        volumeMounts:
          - name: config
            mountPath: /etc/httpd/conf.d
          - name: datavol1
            mountPath: /data1/stash
      volumes:
        - name: config
          configMap: 
            name: http-configs 
        - name: datavol1
          hostPath: 
            path: /data1
            type: Directory 

