apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd-server
  labels: 
    k8s-app: http-caitlin
spec:
  template:
    metadata: 
      labels:
        k8s-app: http
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname:  xcache-11.t2.ucsd.edu
      containers:
      - name: httpd-server
        image: cahung/kubernetes_test
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
          
